### ISSUE TITLE
Question: InkyCal on Pimoroni Inky Frame

### ISSUE THREAD

**Issue by PieterJanSterk** [aceinnolab/Inkycal#261]
Recently, Pimoroni released an Inky Frame, a large 7.3 color e-ink screen with a Pico W built-in. It can run a set of batteries. I immediately thought this would be amazing to run some sort of calendar on it. 

https://shop.pimoroni.com/products/inky-frame-7-3?variant=40541882056787

InkyCal seems like a amazing project and looks like it is the most advanced and feature rich calendar software for e-ink displays at the moment! My question is: at the moment, is it possible to run InkCal on a PicoW, like on this board? Is this something that could be implemented down the road? Or would it be easier to create a seperate server running InkyCal, generating a calendar "image" and displaying it on this screen?

**Comment by aceisace** [comment]
Hi @PieterJanSterk and thanks for your interest in Inkycal!
What a surprise! I also got my hands on the exact same module not long ago! I like the built-in example to display the nasa image of the day 😄 

In regards to using Inkycal with e-paper displays having more three colours, this is currently work in progress (see #feature/238 branch). The problem is that for many years, even three-colour e-paper displays were pretty much rare. Within the last year, 4-colour and 7-colour displays are becoming more easily available and affordable, but developers need to adapt their code first with backward-compatibility. 
This means, a single software would need to support black-white, 3-colour, 4-colour, 7-colour as well as 16-grayscale rendering with optimisations for each display. And unfortunately, this takes some time. As a result, Inkycal has to be refactored first to support these new-generation displays to allow making use of all the colours a display supports. Furthermore, as Inkycal is funded by sales of Inkycal on Tindie and donations, it would mean creating custom hardware which can fit inside a 10mm frame, which takes some time.

While I am working on the feature/238 branch to support 4- and 7-colour displays, I cannot yet provide an exact date when this will be ready. 

With the Pico supporting micropython, displaying a single dynamic image might not sound challenging, but the pre-rendering optimisations require a more powerful processor (which is why most serial e-paper software require some sort of pre-processing to somewhat display an image more or less correctly, some others display text with only large font-sizes since this is less problematic on e-paper displays). 

A more flexible approach would be to serve the image from a server (e.g. running on the Raspberry Pi) and then displaying the image from the pico, but as the pico still draws some power even in sleep/deepsleep, it makes more sense to have the display connected directly to the Raspberry Pi, unless you are trying to serve multiple displays at the same time.
