### ISSUE TITLE
[BUG] - Inkycal runs only once, then quits

### ISSUE THREAD

**Issue by km4vig** [aceinnolab/Inkycal#300]
**Describe the bug**
All I have to change is the -  "model": "epd_7_in_5_v2",  to "model": "image_file",
and the crashing stops, and It continues to refresh with a New image in the slideshow as well as update the other modules as expected.

**Expected behavior**
I view the image \HOMEPI\home\inky\Inkycal\full-screen.png and it reflects the NEW image correctly.
I've attached the two different session runs, the first using 'image_file' the second with 'epd_7_in_5_v2'.

**Comment by km4vig** [comment]
[inky_output.txt](https://github.com/aceinnolab/Inkycal/files/13772263/inky_output.txt)
[inky_output2.txt](https://github.com/aceinnolab/Inkycal/files/13772264/inky_output2.txt)
[inky_log3.txt](https://github.com/aceinnolab/Inkycal/files/13772265/inky_log3.txt)
![full-screen](https://github.com/aceinnolab/Inkycal/assets/22891739/b6c8b48b-d204-48e2-88d8-973eda28cbfd)

**Comment by aceisace** [comment]
Thanks for reporting this issue @km4vig . I have been able to reproduce this error on my end. Thanks to your log outputs, I have been able to find the issue. The cause for this error is not with Inkycal, but with the drivers provided from waveshare, which after a long-due update are not working as expected. The fix is already underway and will be pushed to main soon once I have tested it on my end. 

Please note this issue is the exact same issue as issue #301 and will be closed to avoid duplicated issues. You can continue the conversation and post comments in #301

**Comment by aceisace** [comment]
@km4vig 
Thank you for your patience! The fix I have been testing to fix this problem seems to be working!

Please run the following to fix this issue:
```sh
cd ~/Inkycal
source venv/bin/activate
pip install gpiozero
git pull
sudo reboot
```
